services:
  drtest-portfolio:
    image: drtest-portfolio:latest
    container_name: drtest
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drtest.rule=Host(`drtest.webhost.atsnet.in`)"
      - "traefik.http.routers.drtest.entrypoints=websecure"
      - "traefik.http.routers.drtest.tls.certresolver=cloudflare" # Changed from letsencrypt
      - "traefik.http.services.drtest.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
